name: ci

on: push

permissions:
  contents: read
  packages: write

jobs:
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run check

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Cargo checks
        run: cargo check

      - name: Run Cargo tests
        run: cargo test

  build:
    needs: [test-web, test-backend]
    uses: ldobbelsteen/ghcr-build-push/.github/workflows/main.yml@v1
